# These are supported funding model platforms

github: KenMwaura1
# custom: ['https:paypal.com/kenzmwaura1@gmail.com']
ko_fi: kenmwaura1
open_collective: kenmwaura1
custom: ['https://https://www.buymeacoffee.com/kenmwaura1']